### ISSUE TITLE
Import error on colab with version 1.5.1

### ISSUE THREAD

**Issue by akshay-krishnan** [google-research/dataclass_array#93]
I get the following error when simply installing and importing dataclass_array on a colab.

```
!pip install dataclass-array

import dataclass_array as dca
```

raises: 

```
[/usr/local/lib/python3.10/dist-packages/dataclass_array/array_dataclass.py](https://localhost:8080/#) in DataclassArray()
    582   # ====== Internal ======
    583 
--> 584   @epy.cached_property
    585   def _all_fields_empty(self) -> bool:
    586     """Returns True if the `dataclass_array` is invalid."""

AttributeError: module 'etils.epy' has no attribute 'cached_property'
```

Not sure what I am missing. Any help would be great. Thanks in advance!

**Comment by Conchylicultor** [comment]
Thank for reporting. Please upgrade to 1.5.2 which fix this issue already.

**Comment by Conchylicultor** [comment]
Oh, I think the issue is that 1.5.2 drop Python 3.10 support, while Colab is still running on 3.10.

**Comment by akshay-krishnan** [comment]
Yes, indeed!

> Oh, I think the issue is that 1.5.2 drop Python 3.10 support, while Colab is still running on 3.10.

**Comment by Conchylicultor** [comment]
Can you try to install dataclass_array from Git directly in Colab (`pip install git+https://...`) ? 

Looking at the 1.5.2 diff, I think it should still work on 3.10: https://github.com/google-research/dataclass_array/compare/v1.5.1...v1.5.2

If this work, then you can send a cl to change then `.toml` back to 3.10
